// SPDX-License-Identifier: Apache-2.0
#pragma once

/* Verified beken_robot panel power/reset/backlight and speaker amplifier. */
#define GPIO_DEFAULT_DEV_CONFIG \
{ \
    {GPIO_5, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_GPIO_OUTPUT, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE}, \
    {GPIO_7, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_GPIO_OUTPUT, \
     GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    /* Robot V2 wires its four buttons as two resistor ladders on ADC pads, so
     * the pads must stay high-Z with no pull: an internal pull-up loads the
     * divider and skews the millivolts the adc_key component compares against.
     * GPIO13 is ADC15 (S2/S3), GPIO28 is ADC4 (S4/S5). The board's fifth
     * button drives the SoC CEN pin and never reaches firmware. */ \
    {GPIO_13, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_28, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    /* GPIO8 and GPIO9 are the 32.768 kHz crystal (P8/32K_XO, P9/32K_XI), not
     * buttons. Driving them as pulled-up inputs made the pads flap and fire
     * phantom key presses that put the device in a reboot loop, so they follow
     * the vendor board table and stay high-Z. GPIO12 has no pad at all on the
     * BK7259V2 QFN128 package, so it is not listed. */ \
    {GPIO_8, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_9, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_20, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_GPIO_OUTPUT, \
     GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    /* Robot V2 dual DMIC (MIC1/MIC2 on the DMIC1 PDM bus). */ \
    {GPIO_49, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_DMIC1_DAT, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_50, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_DMIC1_CLK, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_53, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_GPIO_OUTPUT, \
     GPIO_DEV_INVALID, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
}
