// SPDX-License-Identifier: Apache-2.0
#pragma once

/* CP owns the UART0 console. All product GPIOs are configured by the AP. */
#define GPIO_DEFAULT_DEV_CONFIG \
{ \
    {GPIO_10, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART0_RXD, \
     GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
    {GPIO_11, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART0_TXD, \
     GPIO_DEV_GPIO_INPUT, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, \
     GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, \
     GPIO_DRIVER_CAPACITY_0, GPIO_INIT_ENABLE}, \
}
